# Generated by Django 3.2.2 on 2021-05-14 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_developeruserprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='users.studentuser')),
            ],
        ),
    ]
