# Generated by Django 3.2.2 on 2021-05-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuserprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='developeruserprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=180, null=True),
        ),
    ]
