# Generated by Django 3.2.2 on 2021-05-18 20:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developeruser',
            options={'verbose_name': 'Developer User', 'verbose_name_plural': 'Developer Users'},
        ),
        migrations.AlterModelOptions(
            name='studentuser',
            options={'verbose_name': 'Student User', 'verbose_name_plural': 'Student Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
